# fly.toml app configuration file generated for matamata on 2024-01-16T03:15:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "matamata"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
