name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: test_pw
          POSTGRES_USER: test
        ports:
          - 5432:5432

    steps:
      - name: Checkout repo files
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Install Python package build/install dependencies
        run: pip install --upgrade pip build setuptools

      - name: Install test packages
        run: pip install -e '.[test]'

      - name: Run tests
        run: pytest --cov=src . -vv
